@startuml
skinparam style strictuml

actor User
actor Admin

participant "Login_System" as Login
participant "File_Manager" as FM
participant "Permission System" as PS
participant "Audit_Log" as Log
participant "MySQL DB" as DB

' --- Scenario 1 ---
Admin -> Login : login(email, password)
Login -> Admin : 3diAccesss/ uogilents/
Login --> Login : user_authenticated
Login -> Admin : showDashboard()

Admin -> FM : uploadFile(File, data)
FM -> PS : checkStoragePermison(queryAccessLevel())
PS --> PS : user_authenticated
PS -> DB : access_granted

FM -> FM : saveFile(path, size)
FM -> PS : saveFile(path, size)
PS --> FM : file_saved_status(Pending)

' Adding Audit Log as requested
FM -> Log : logUploadActivity(file_data)

FM -> DB : createEntry("File_Uploaded", ip_address)

' --- Scenario 2 ---
Admin -> Login : login(email, password)
Login -> Admin : showAdminPanel()
Admin -> Login : viewPendingFiles()

FM -> PS : [Access Denied]
PS -> DB : Access Denied
DB -> Admin : Access Denied

Admin -> FM : approveFile(it_id)
FM -> PS : [Access Denied]

' Adding Audit Log as requested
PS -> Log : logApprovalActivity(it_id)

PS -> DB : Access denile
DB -> FM : 8. Send File
@enduml